<a href="https://colab.research.google.com/github/DaruHashida/MyPyTorch/blob/main/FirstPytorchExercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00. PyTorch Fundamentals


In [ ]:
print('I\'d like to perfectly learn PyTorch')

I'd like to perfectly learn PyTorch


Давайте попробуем посмотреть, что за версия у видеокарты:

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


##Introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

PyTorch tensorsare created using `torch.Tensor{}` -= https://pytorch.org/docs/stable/tensors.html

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
TENSOR1 = torch.tensor([[[3, 2, 1],
                         [7, 18, 124],
                         [15, 90, 60]],
                        [[19, 18, 17],
                         [16, 15, 14],
                         [10, 8, 7]]])
TENSOR1

tensor([[[  3,   2,   1],
         [  7,  18, 124],
         [ 15,  90,  60]],

        [[ 19,  18,  17],
         [ 16,  15,  14],
         [ 10,   8,   7]]])

In [ ]:
TENSOR1.ndim

3

In [ ]:
TENSOR1.shape

torch.Size([2, 3, 3])

###Random tensors

Why random tensors???

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data-> update random numbers-> look at data-> update random numbers`

In [ ]:
#Create a random tensor of size [3,4]

random_tensor=torch.rand(1,3,4)
random_tensor

tensor([[[0.5330, 0.9270, 0.5722, 0.5464],
         [0.7611, 0.8534, 0.4754, 0.5093],
         [0.7929, 0.4531, 0.3862, 0.4404]]])

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224)) #height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
random_tensor2=torch.rand(3,4,5,6)
random_tensor2

tensor([[[[0.6047, 0.6848, 0.7304, 0.8194, 0.2221, 0.0331],
          [0.3614, 0.2196, 0.3077, 0.4263, 0.3784, 0.0754],
          [0.5788, 0.4831, 0.8578, 0.2789, 0.7726, 0.0038],
          [0.3373, 0.7772, 0.7788, 0.1798, 0.5603, 0.1713],
          [0.4183, 0.7306, 0.7074, 0.7502, 0.3024, 0.3181]],

         [[0.1625, 0.5199, 0.6627, 0.0945, 0.4706, 0.4538],
          [0.6468, 0.4079, 0.3545, 0.6595, 0.8388, 0.9183],
          [0.1346, 0.6755, 0.8925, 0.5572, 0.9333, 0.7588],
          [0.6126, 0.2275, 0.8054, 0.2960, 0.4558, 0.5349],
          [0.2173, 0.4326, 0.9833, 0.3911, 0.7762, 0.5204]],

         [[0.0933, 0.9364, 0.4509, 0.4390, 0.8419, 0.7142],
          [0.7069, 0.1756, 0.4223, 0.2135, 0.1514, 0.3402],
          [0.1664, 0.7737, 0.5875, 0.7212, 0.7769, 0.9032],
          [0.9862, 0.0781, 0.7051, 0.3249, 0.9876, 0.6367],
          [0.1194, 0.7492, 0.6835, 0.0853, 0.6342, 0.9029]],

         [[0.4958, 0.7995, 0.3782, 0.7638, 0.0586, 0.8244],
          [0.7495, 0.7246, 0.3141,

### Zeros and ones

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
#Use torch.range()
one_to_ten = torch.arange(start=0,end=11,step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating tensors like
ten_zeroes=torch.zeros_like(one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors i'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what dtype is the tensor
                               device=None, #default "cpu", maybe "cuda"
                               requires_grad=False #track gradients with tensor operations
                               )
float_32_tensor



tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor*float_16_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. To get dtype
2. To get shape
3. To get device

In [ ]:
some_tensor = torch.rand(3,4, device="cpu")
some_tensor

tensor([[0.4382, 0.3103, 0.2009, 0.1810],
        [0.0944, 0.3712, 0.9083, 0.1940],
        [0.6631, 0.6212, 0.9447, 0.8653]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")


tensor([[0.4382, 0.3103, 0.2009, 0.1810],
        [0.0944, 0.3712, 0.9083, 0.1940],
        [0.6631, 0.6212, 0.9447, 0.8653]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


###Manipulating tensors (tensor operations)
Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
#Create a tensor and add 100 to it: addition
tensor=torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
#Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [ ]:
#Substract 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
#Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural network and deep learning

1. Element-wise multiplication (scalar multiplication)
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
1rows->2columns

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,4))

tensor([[1.1396, 0.6853, 0.7934, 0.8170],
        [1.2082, 0.7385, 0.6347, 1.0769]])

In [ ]:
#Element wise multiplication
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
#Matrix multiplication by hand
1*1+2*2+3*3

14

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 448 µs, sys: 0 ns, total: 448 µs
Wall time: 457 µs


In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 0 ns, sys: 37 µs, total: 37 µs
Wall time: 40.3 µs


tensor(14)

### One of the most common errors in deep learning: shape errors



In [ ]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                       [3, 4],
                       [5,6]])
tensor_B= torch.tensor([[7,10],
                       [8, 11],
                       [9,12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: ignored

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
#The matrix multiplication operation works when tensor_b is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [ ]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape: tensor_A.T = {tensor_A.T.shape}, tensor_B = {tensor_B.shape} (same shape as above)")
print(f"Multiplying: {tensor_A.T.shape} @ {tensor_B.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A.T, tensor_B)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape: tensor_A.T = torch.Size([2, 3]), tensor_B = torch.Size([3, 2]) (same shape as above)
Multiplying: torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimensions must match
Output:

tensor([[ 76, 103],
        [100, 136]])

Output shape: torch.Size([2, 2])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
#Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#Find the mean, requires a tensor of torch.float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() #should be float, not a long

(tensor(45.), tensor(45.))

In [ ]:
#Find the sum:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

### Finding the positional min, max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Find the position in tensor that has a minimum value, returns index position of target tensor where minimum value accurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
#Find the position in tensor which has a max value
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(90)

###Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view jf an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimmensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
#Let's create a tensor
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the originak)
z[:,0]=5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.hstack([x,x,x,x])
x_stacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
#torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
#torch.permute() - rearranges dimensions of a target tensor in a specified order
x_original = torch.rand(224,224,3) #[height, width, colour_channes]

#Permute the originak tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"Old shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #


Old shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 73212

In [ ]:
x_permuted

tensor([[[7.3212e+04, 9.5755e-01, 9.5219e-01,  ..., 1.3134e-01,
          4.8456e-01, 9.8392e-01],
         [6.4684e-01, 5.8055e-01, 4.1503e-02,  ..., 7.6111e-01,
          4.7655e-01, 7.9119e-01],
         [2.3842e-02, 8.4205e-01, 3.2151e-01,  ..., 7.2879e-01,
          5.7773e-01, 4.9353e-01],
         ...,
         [5.8282e-01, 6.6587e-01, 9.4279e-01,  ..., 4.4984e-01,
          8.9607e-01, 4.7936e-01],
         [5.3750e-01, 4.5518e-01, 9.6555e-01,  ..., 2.2490e-01,
          6.0065e-02, 3.6089e-01],
         [4.4102e-01, 8.9062e-01, 2.7321e-01,  ..., 4.8258e-01,
          8.1093e-02, 6.6162e-01]],

        [[1.6810e-01, 2.5280e-02, 4.2445e-01,  ..., 7.6652e-01,
          4.6933e-01, 1.4851e-01],
         [5.9489e-01, 6.9737e-01, 4.7673e-01,  ..., 2.6261e-01,
          7.0709e-01, 1.9952e-01],
         [1.6368e-01, 3.7138e-01, 1.9207e-02,  ..., 9.4497e-01,
          3.4449e-01, 3.7249e-01],
         ...,
         [1.8387e-01, 4.4699e-01, 9.9151e-01,  ..., 6.2387e-01,
          4.561

### Indexing (selecting data from tensors)
Is similar to indexing with NumPy.

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Let's index on the middle bracket
x[0][0]

tensor([1, 2, 3])

In [ ]:
#Let's index on the most inner brackets
x[0][2][2]

tensor(9)

In [ ]:
#You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [ ]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#Index on x to return 3, 6, 9
x[0,:,2]

tensor([3, 6, 9])

##PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensot -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
from numpy.lib import arraysetops
#NumPy array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)#.type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#If i'm going from numpy to torch, datatype is float64, pytorch reflects numPy's default datatype!!!
tensor.dtype

torch.float64

In [ ]:
#Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change the tensor, what happens to `numpy_tensor`?
tensor=tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try to make them better representations of the data -> again -> again -> again

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seeds does is "flavour" the randomness

In [ ]:
import torch
torch.rand(3,3)
#Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6114, 0.2841, 0.6510, 0.7475],
        [0.1301, 0.3453, 0.6816, 0.9203],
        [0.4738, 0.5496, 0.9707, 0.5160]])
tensor([[0.4002, 0.8781, 0.1296, 0.6716],
        [0.1108, 0.1105, 0.7689, 0.8759],
        [0.3856, 0.2608, 0.1098, 0.2161]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
##Let's make some random but reproducible tensors
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED);
random_tensor_C = torch.rand(3,4)
#If you want to use manual seed, it works only once for each block of code
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED);
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running tensors and PyTorch objects on GPUs and making faster computations

GPUs=faster computation on number -> CUDA + NVIDIA working behind the scenes to make all hunky dory.

###1.Getting a GPU

1. Using GoogleColab for a free GPU (options to upgrade as well)
2. Use user's own GPU - takes a little bit of setup and requires the investmen of purchasing a GPU, there's lots of options
3. Use cloud computing- GCP,AWS,Azure services allow torent computers on the cloud and access them

For 2, 3 Pytorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation:https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

Wed Aug  9 13:24:59 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

###2. Check for GPU access with PyTorch

In [ ]:
#Check for GPU access with PyTorch

import torch

torch.cuda.is_available()


True

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
#Count number of devices
print(torch.cuda.device_count());

1


## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU makes faster computations.

In [ ]:
# Creating a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor `to` GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
#If tensor is on GPU, can't ransform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu


array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

##Exercises & Extra-curriculum

In [ ]:
See https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises